name: Ubuntu Modules C/C++ CI

on:
  push:
    branches: [ IEVector ]
  pull_request:
    branches: [ IEVector ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get update && sudo apt-get install xorg-dev && sudo apt install libgl1-mesa-dev &&sudo apt-get install -y gcc-8 g++-8 && sudo apt-get install libalut-dev && ./WizardJump/GenerateProjectGNU.sh
    - name: make
      run: make
