name: MacOS Debug Build

on:
  push:
    branches: [ Editor-Artifacts-Macos ]
  pull_request:
    branches: [ Editor-Artifacts-Macos  ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: chmod +x ./ImpulseEditor/Generate/GenerateProject.command
    - name: Generate and Make Static
      run: ./ImpulseEditor/Generate/GenerateProject.command xcode4 --os=macosx --build-engine --build-editor && git clean -d -f -x && xcodebuild -workspace  ImpulseEditor.xcworkspace -scheme ImpulseEditor -configuration Debug build
    - name : Generate and Make Dynamic
      run: ./ImpulseEditor/Generate/GenerateProject.command xcode4 --os=macosx --hot-reload --build-engine --build-editor && xcodebuild -workspace ImpulseEditor.xcworkspace -scheme ImpulseEditor -configuration Debug clean && git clean -d -f -x && xcodebuild -workspace  ImpulseEditor.xcworkspace -scheme ImpulseEditor -configuration Debug build
    - name : Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with : 
        name: ImpulseEditor
        path: ImpulseEditor/Bin/Debug-macosx-x86_64/