name: MacOS Release Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master  ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: chmod +x ./ImpulseEditor/Generate/GenerateProject.command
    - name: Generate and Make Static
      run: ./ImpulseEditor/Generate/GenerateProject.command xcode4 --os=macosx --build-engine --build-editor && xcodebuild -workspace  ImpulseEditor.xcworkspace -scheme ImpulseEditor -configuration Release build
    - name : Generate and Make Dynamic
      run: git clean -d -f -x && ./ImpulseEditor/Generate/GenerateProject.command xcode4 --os=macosx --hot-reload --build-engine --build-editor && xcodebuild -workspace  ImpulseEditor.xcworkspace -scheme ImpulseEditor -configuration Release build