name: MacOS Debug Build

on:
  push:
    branches: [ Editor ]
  pull_request:
    branches: [ Editor ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate and Make Static
      run: ./ImpulseEditor/Generate/GenerateProject.sh gmake2 --os=macosx --build-engine --build-editor && make config=debug
    - name : Generate and Make Server
      run: ./ImpulseEditor/Generate/GenerateProject.sh gmake2 --os=macosx --server --build-engine && make clean && make config=debug
    - name : Generate and Make Dynamic
      run: ./ImpulseEditor/Generate/GenerateProject.sh gmake2 --os=macosx --hot-reload --build-engine --build-editor && make clean && make config=debug
    - name : Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with : 
        name: ImpulseEditor
        path: ImpulseEditor/Bin/Debug-macosx-x86_64/