name: Ubuntu Make Editor

on:
  push:
    branches: [ Editor ]
  pull_request:
    branches: [ Editor ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get update && sudo apt-get install xorg-dev && sudo apt install libgl1-mesa-dev && sudo apt-get install -y gcc-8 g++-8 && sudo apt-get install libglib2.0-dev && sudo apt-get install libgtk-2-dev && sudo apt-get install libalut-dev && chmod +x ./vendor/premake/premake5_linux && chmod +x ./ImpulseEditor/Generate/GenerateProject_Linux.sh && ./ImpulseEditor/Generate/GenerateProject_Linux.sh 
    - name: make
      run: make config=release
